resilience4j.circuitbreaker.instances.downstreamService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.downstreamService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.downstreamService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.downstreamService.waitDurationInOpenState=10000spring.application.name=apigateway
